version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-nestjs-base
    ports:
      - '3050:3050'
    depends_on:
      - redis
    networks:
      - backend-network

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - backend-network

networks:
  backend-network:
    name: backend-network
